import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";
import { MobileBottomNav } from "@/components/shared/MobileBottomNav";
import QueryProvider from "@/providers/query-provider";

import { ImpersonationProvider } from "@/providers/impersonate-provider";
import ImpersonationAlert from "@/components/impersonation-alert";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ImpersonationProvider>
            <QueryProvider>
              <ImpersonationAlert />
              {children}
              <MobileBottomNav />
              <Toaster expand={true} />
            </QueryProvider>
          </ImpersonationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
